### ISSUE TITLE
update bile acid methods

### ISSUE THREAD

**Issue by siobhon-egan** [jwist/request#13]
Request from @sungchin to update MS bile acid methods.
Can you please amend L180-L182 in [classRequestList.R](https://github.com/jwist/request/blob/master/R/classRequestList.r) to the following:

                msFile <- "BileAcids_MS_2022"
                msTunFile <- "BileAcids_Tune_2022"
                inletFile <- "BileAcids_LC_2022"

**Comment by jwist** [comment]
Yes I can, and I will. But what are the run order that need to be produced using this new methods?

**Comment by sungchin** [comment]
Can you please see the run order as listed in the attached file? It would similar to worklist produced for ROCIT if that's help. Many thanks

[2022_Worklist-Example_BileAcids_PAT-02.csv](https://github.com/jwist/request/files/8457243/2022_Worklist-Example_BileAcids_PAT-02.csv)
