### ISSUE TITLE
New matrixID

### ISSUE THREAD

**Issue by siobhon-egan** [jwist/request#14]
Can I please request new addition to sample type to `matrixID`

Can we please add the following:

10	BALF	Bronchoalveolar lavage fluid

https://docs.google.com/spreadsheets/d/e/2PACX-1vQs_oa0dMN6RE837QQ6GgQHFQr85SnjJZExxBarrWhEClCqHWEjEEp_bhtNwpbAlWpucbda9RhrkWTp/pub?gid=481322438&single=true&output=tsv

**Comment by jwist** [comment]
done
