### ISSUE TITLE
NMR holder number

### ISSUE THREAD

**Issue by siobhon-egan** [jwist/request#17]
Issue with revised NMR run order generation.
The "HOLDER" is not formatting correctly and is giving a new position for each experiment even though sample is the same.

Not sure if it is getting this information from [`getrun.r`](https://github.com/jwist/request/blob/6a9350f71f067a55e25d28a3c2c42f8ac3a6e694/R/getRun.r).

Issues noticed by Philipp from diabetes/exercise run orders.

**Comment by jwist** [comment]
fixed
